import { Property } from '@/types/property';

export const mockProperties: Property[] = [
  {
    id: "mock-1",
    title: "Casa Centro Histórico",
    description: "Hermosa casa ubicada cerca de la Plaza General Francisco Ramírez, con amplios espacios y excelente iluminación natural.",
    price: 120000,
    location: "Centro, Concepción del Uruguay",
    latitude: -32.4839,
    longitude: -58.2372,
    imageUrls: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80"],
    status: "for_sale",
    type: "house",
    featured: true,
    amenities: {
      bedrooms: 3,
      bathrooms: 2,
      squareMeters: 150,
      parking: true,
      pool: false,
      garage: true,
      garden: true,
      terrace: true,
      airConditioning: true,
      furnished: false
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "mock-2",
    title: "Cabaña Vista Río",
    description: "Confortable cabaña cerca del balneario, ideal para disfrutar del verano y la tranquilidad.",
    price: 85000,
    location: "Zona Banco Pelay, Concepción del Uruguay",
    latitude: -32.4431,
    longitude: -58.2045,
    imageUrls: ["https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80"],
    status: "for_sale",
    type: "house",
    featured: true,
    amenities: {
      bedrooms: 2,
      bathrooms: 1,
      squareMeters: 90,
      parking: true,
      pool: true,
      garage: false,
      garden: true,
      terrace: true,
      airConditioning: true,
      furnished: true
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "mock-3",
    title: "Quinta Histórica",
    description: "Amplísima quinta en las afueras, cerca del Palacio San José. Terreno extenso y parquizado.",
    price: 250000,
    location: "Ruta 39, Concepción del Uruguay",
    latitude: -32.4045,
    longitude: -58.3075,
    imageUrls: ["https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80"],
    status: "for_sale",
    type: "land",
    featured: false,
    amenities: {
      bedrooms: 4,
      bathrooms: 3,
      squareMeters: 400,
      parking: true,
      pool: true,
      garage: true,
      garden: true,
      terrace: false,
      airConditioning: true,
      furnished: false
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "mock-4",
    title: "Departamento Céntrico Moderno",
    description: "Departamento a estrenar cerca de la Terminal de Ómnibus. Excelente conectividad.",
    price: 65000,
    location: "Centro Norte, Concepción del Uruguay",
    latitude: -32.4833,
    longitude: -58.2492,
    imageUrls: ["https://images.unsplash.com/photo-1502672260266-1c1de2d93688?auto=format&fit=crop&w=800&q=80"],
    status: "for_sale",
    type: "apartment",
    featured: true,
    amenities: {
      bedrooms: 1,
      bathrooms: 1,
      squareMeters: 55,
      parking: false,
      pool: false,
      garage: false,
      garden: false,
      terrace: true,
      airConditioning: true,
      furnished: false
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "mock-5",
    title: "Chalet Residencial",
    description: "Propiedad de categoría en barrio residencial, a pasos del Hospital Urquiza.",
    price: 180000,
    location: "Barrio Hospital, Concepción del Uruguay",
    latitude: -32.4781,
    longitude: -58.2562,
    imageUrls: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80"],
    status: "for_sale",
    type: "house",
    featured: false,
    amenities: {
      bedrooms: 3,
      bathrooms: 3,
      squareMeters: 220,
      parking: true,
      pool: false,
      garage: true,
      garden: true,
      terrace: true,
      airConditioning: true,
      furnished: false
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
